#!/bin/bash

if [ -z $QDIR ]; then
	echo "Please set QDIR (like \"export QDIR=~/quantonium/install\")"
	echo
	exit 1
fi

sudo QDIR=$QDIR PYTHONPATH="$QDIR/lib:$CWD" LD_LIBRARY_PATH=$QDIR/lib python3 run_ns.py "$@"
